[package]
name = "file-web"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.12"
minijinja = "0.30.7"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
